name: "Nix"
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  tests:
    strategy:
      matrix:
        builder: [crane, brp]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Test checks
      run: nix build -L --keep-going --show-trace --impure --expr '(builtins.getFlake (toString ./.)).${{ matrix.builder }}Tests.checks.${builtins.currentSystem}'
    - name: Test shells
      run: nix build -L --keep-going --show-trace --impure --expr '(builtins.getFlake (toString ./.)).${{ matrix.builder }}Tests.shells.${builtins.currentSystem}'
    - name: Test packages
      run: nix build -L --keep-going --show-trace --impure --expr '(builtins.getFlake (toString ./.)).${{ matrix.builder }}Tests.packages.${builtins.currentSystem}'
  build-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#nci-cli
